baseURL: 'https://robertofinnisaro.com/'
title: Home
theme: PaperMod

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10


params:
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false

    #profile inital
    profileMode:
        enabled: true
        title: robertofinnisaro
        buttons:
            - name: Docs
              url: /docs/
    
    homeInfoParams:
        Title: "robertofinnisaro"
        Content: >
            Welcome to my personal site

    