baseURL: 'https://robertofinnisaro.com/'
title: Home
theme: PaperMod

params:

    #profile inital
    profileMode:
        enabled: true
        title: robertofinnisaro
        buttons:
            - name: Docs
              url: /docs/
    
    homeInfoParams:
        Title: "robertofinnisaro"
        Content: >
            Welcome to my personal site

    