baseURL: 'https://robertofinnisaro.com/'
title: Home
theme: github.com/adityayelange/hugo-PaperMod
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: ":En:"
        languageAltTitle: English
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        profileMode:
            enabled: true
            title: robertofinnisaro
            # imageUrl: "https://github.com/hampusborgos/country-flags/blob/main/svg/gb.svg"
            # imageTitle: ProfileMode image
            # imageWidth: 120
            # imageHeight: 120
        menu:
            main:
                - name: Docs
                  url: docs/
                  weight: 10
                - name: Archive
                  url: archives/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON


params:
    env: production
    defaultTheme: auto
    disableThemeToggle: false
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: false
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false

    label:
      text: "Home"
      icon: /apple-touch-icon.png
      iconHeight: 35

    #profile inital
    profileMode:
        enabled: ture
        title: robertofinnisaro
        imageUrl: "#"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        # buttons:
        #     - name: Docs
        #       url: /docs/
    
    homeInfoParams:
        Title: "robertofinnisaro"
        Content: >
            Welcome to my personal site

    
