baseURL = 'https://robertofinnisaro.com/'
languageCode = 'en-us'
title = 'Home'
theme = 'PaperMod'

[Params]
    #profile inital
    [profileMode]
        enabled = true
        title = "robertofinnisaro"
        subtitle = "Welcome to my personal site"

    # --- Start sidebar config ---
    # Number of posts that will be displayed in sidebar
    sidebarRecentLimit = 5
    
    # Sidebar header
    sidebarHeader = "Sidebar Header"

    # Sidebar menu
    sidebarMenuEnabled = true
    sidebarMenuHeader = "Sidebar Links"

    # Sidebar links
    github = "https://github.com/robertofinnisaro/"

    # --- End sidebar config ---